name: Inject APK / XAPK (linux-x64 & win-64)

on: 
  workflow_dispatch:
  schedule: 
    - cron: '0 8 * * *'

jobs:
  inject:
    runs-on: ubuntu-24.04

    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Environment
        run: |
          sudo apt update
          sudo apt install php php-curl curl libnss3 nss-plugin-pem ca-certificates python3 openjdk-17-jdk -y

      - name: Run Script
        run: bash run.sh
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: il2cpp
          retention-days: 1
          path: |
            ./global-metadata.dat
            ./libil2cpp.so
            ./appVersion.txt
            ./Il2CppDumper.zip
            ./*_signed.apk

  dump:
    runs-on: windows-latest
    needs: inject

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: il2cpp

      - name: Dumping
        run: |
          unzip Il2CppDumper.zip
          New-Item -Path output -ItemType Directory
          powershell "./Il2CppDumper.exe libil2cpp.so global-metadata.dat output; echo Finished."
          $VERSION=$(Get-Content appVersion.txt)
          echo "VERSION=v$VERSION" >> $env:GITHUB_ENV
          echo $env:GITHUB_ENV
          cat $env:GITHUB_ENV

      - name: Uploading Dump.cs
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            ./output/dump.cs
            ./*_signed.apk
