name: Inject APK / XAPK (ubuntu-latest)

on: 
  workflow_dispatch:

jobs:
  inject:
    runs-on: ubuntu-20.04

    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Environment
        run: |
          sudo dpkg --add-architecture i386
          wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
          sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
          sudo apt install --install-recommends winehq-stable
          sudo apt update
          sudo apt install php php-curl curl libnss3 nss-plugin-pem ca-certificates python3 openjdk-17-jdk -y

      - name: Run Script
        run: bash run.sh
    
      - name: Uploading Packages
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            ./*_signed.apk
            ./output/dump.cs
