name: Inject APK / XAPK (ubuntu-latest)

on: 
  workflow_dispatch:

jobs:
  inject:
    runs-on: ubuntu-20.04

    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Environment
        run: |
          sudo dpkg --add-architecture i386
          sudo mkdir -pm755 /etc/apt/keyrings
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/focal/winehq-focal.sources
          sudo apt update
          sudo apt install php php-curl curl libnss3 nss-plugin-pem ca-certificates python3 openjdk-17-jdk wine wine32 -y


      - name: Run Script
        run: bash run.sh
    
      - name: Uploading Packages
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            ./*_signed.apk
            ./output/dump.cs
